runtime: nodejs16

handlers:
  - url: /(.*)
    static_files: build/\1
    upload: build/.*
    http_headers:
      Cache-Control: public, max-age=31536000
  - url: /.*
    static_files: build/index.html
    upload: build/index.html