version: 0.2

phase: 
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://codepipeline-eu-north-1-671641659629/Cross-Admin4/
      - aws cloudfront create-invalidation --distribution-id EBCDGGYOSVD1 --path /\*